name : shell commands 

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello String"
      - name: multiple script
        run: |
          node -v
          npm -v
  
  run-window-commands:
    runs-on: windows-latest
    needs: ["run-shell-commands"]
    steps:
      - name: directory 
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash


